### ISSUE TITLE
[skip ci] on bump_version

### ISSUE THREAD

**Issue by yonicd** [krlmlr/fledge#11]
in a CI environment wouldnt having a `[skip ci]` appended to the commit message make sense on a bump_version call since nothing should be changing and forcing the CI to run just for that seem overkill I would think.

**Comment by krlmlr** [comment]
What if the CI updates the documentation website (pkgdown) which displays the version number?

**Comment by yonicd** [comment]
maybe a param in the call to control it? is that example with `{pkgdown}` the usual package maintenance case?

**Comment by krlmlr** [comment]
I'd argue the baseline is to run CI, because {pkgdown} is a very common use case. Let's revisit options if/when we have configuration settings, because an argument would clutter the interface and you'd have to remember it every time you use it.

**Comment by krlmlr** [comment]
Closing in favor of the more recent duplicate #24, which also shows a workaround.

**Comment by yonicd** [comment]
neat. thanks!
