### ISSUE TITLE
Add hyperlinks to issues

### ISSUE THREAD

**Issue by Robinlovelace** [krlmlr/fledge#16]
Great package idea, I saw you developed this concept a while back, great to see it formalised in a package!

One question: why not include hyperlinks in the NEWS? That would encourage people to go to the source code and get involved is my thinking and why I try to manually add links to issues - see https://github.com/ropensci/stplanr/blob/master/NEWS.md  for an example. If it's not deemed best practice to include links I can stop, but seeing as it's an md file, I see no issues.

**Comment by krlmlr** [comment]
The pkgdown version has the links: https://tibble.tidyverse.org/news/index.html . They are also rendered in the GitHub release notes, e.g. https://github.com/tidyverse/tibble/releases/tag/v2.0.1. It feels redundant to add them to the source file.

**Comment by Robinlovelace** [comment]
Aha it's `pkgdown` magic. Thanks for the clarification!
