### ISSUE TITLE
Keep/make package composable to allow for different workflows

### ISSUE THREAD

**Issue by petermeissner** [krlmlr/fledge#17]
**This is more of a discussion issue ...**

I really like the broad motivation for the package and the functionality it provides - bumping version numbers, collecting commit messages. 

What I do not like is the specific workflow it modelling - collecting only commit messages with marked with "*" or "-", bumping version to dev by default, ... 

I think allowing users to use the functionality without having to fully buy in the one preset way of doing things would really benefit the package to make it a good fit for a broader audience. 

**A strategy for this could be quite simple:**

- keep the preset way of doing things 
- allow users to use functionality separately

**User story**

To give those thoughts some flesh, I can imagine the following workflow - or some variant of that:

- I develop the package and once in a while I increase the version number (using e.g. `fledge::version_up_patch()`, `fledge::version_up_minor()`, `fledge::version_up_major()`) and best of all the date gets updated automatically as well 
- when some development cycle is done or CRAN publication day comes nearer I want the news file to get an update so I do `update_news_missing()` and all un-newsed tags get added to the NEWS.md while all older entries stay as is
- then I go through NEWS.md and put some polish on the commit messages - I likely will throw out some stuff because its to narrow or noisy or add some stuff that might describe the broader picture
- Commit, push, done.

**Last words**

Maybe this would overstretch the packages purpose but I think allowing the worker-horse functionality to be re-composed into new/modified workflows would be a huge benefit.

**Comment by krlmlr** [comment]
I don't fully understand what `update_news_missing()` is supposed to do.

Happy to review a PR that splits `update_version()` into updating `DESCRIPTION` and adding the `NEWS` header. It's also worth reviewing the workflows that {usethis} already offers.

**Comment by petermeissner** [comment]
(1)
`update_news_missing()` would add all items and tags that are missing from the NEWS, not only those since the last tag - but maybe this is not as trivial as it sounds and has to wait I actually have a clear understanding of how to do this technically.

(2)
I am happy to work on a PR ... I am not 100% sure I understand this one though:
> Happy to review a PR that splits update_version() into updating DESCRIPTION and adding the NEWS header. It's also worth reviewing the workflows that {usethis} already offers.

Maybe, I crank something out (that fits my understanding) and you just have a look and say if it fits or we have to do some adjustments.

**Comment by krlmlr** [comment]
`update_news()` is already fairly flexible, see [`?update_news](https://krlmlr.github.io/fledge/reference/update_news.html). An example is missing though.

I'd greatly appreciate a PR outlining your workflow using existing tools in fledge (and extending them where necessary).
