### ISSUE TITLE
top-level commit is not added to the NEWS file

### ISSUE THREAD

**Issue by pat-s** [krlmlr/fledge#23]
When calling `bump_version()` on https://github.com/ropenscilabs/travis/commit/e92adcf7d302db9217b4251093c7c6308ca1c168

I get 

```
# travis 0.3.0.9003

- Same as previous version.


# travis 0.3.0.9002

- Internal changes only.


# travis 0.3.0.9001
```

and here I am missing the top-level commit which 

```r
> get_top_level_commits(since = get_last_tag())
[[1]]
[e92adcf] 2020-01-03: Add own `browse_travis()` (#128)
```

shows. Shouldn't it be added as a bullet point to v0.3.0.9002?

**Comment by krlmlr** [comment]
The message in ropenscilabs/travis@e92adcf doesn't have a bullet point, you need to edit the commit message before merging.

**Comment by pat-s** [comment]
No, this was just meant to serve as the commit revision. 

This one https://github.com/ropenscilabs/travis/commit/db82417d85824807ca8fedd4db5292042c05a9ec has one and was added after tag v0.3.0.9001.

hence I'd assume that calling `bump_version()` on https://github.com/ropenscilabs/travis/commit/583544d78e28bd19a3678c59e22667485702f4b7 would add it to NEWS.md

Reprex:

```
cd <ropenscilabs/travis>

git checkout 583544d78e28bd19a3678c59e22667485702f4b7

fledge::bump_version()
```

what am I doing wrong?

**Comment by krlmlr** [comment]
https://github.com/ropenscilabs/travis/commit/db82417d85824807ca8fedd4db5292042c05a9ec is not a top-level commit. The merge commit that happens when you merge a pull request is one. Add a bullet to the message when merging the PR, then it's included here.

**Comment by pat-s** [comment]
Ahh - I thought every commit started with either `-` or `*` is one. But this only applies to regular commits and for PRs its only the final merge commit?

The following statement in the README suggests this a bit

> From now on, use bullet points (* or -) in your commit or merge messages to indicate the messages that you want to include in NEWS.md

if my assumption holds true, maybe one can add that for PRs only the final merge commit counts?

**Comment by krlmlr** [comment]
Yes, we need a better definition/explanation for "top-level commit".
