### ISSUE TITLE
Adding date to a version

### ISSUE THREAD

**Issue by daattali** [krlmlr/fledge#29]
I hink it's very helpful to show a date along each version in the NEWS file, at least as an optional parameter. I also think that should become the standard, but that's a different discussion... :)

**Comment by daattali** [comment]
For example

```
# mypackage v1.1.* (Date: TBD)

# mypackage v1.1.0 (2020-05-20)
...

# mypackage v 1.0.0 (2019-08-10)
...
```

**Comment by krlmlr** [comment]
We had this before. If we could teach pkgdown to use or ignore that date, I'm all ears for adding it back.

**Comment by daattali** [comment]
What do you mean? The page rendering breaks down when there's a date on the same line with the version?

**Comment by krlmlr** [comment]
The date appears twice, last time I checked which was some time ago. Have things changed?

**Comment by daattali** [comment]
I don't know, I don't use pkgdown :p

**Comment by daattali** [comment]
But last time I had this convo with hadley over twitter (few years ago) he didn't seem too enthusiastic about adding dates to NEWS so I can understand if it's not supported

**Comment by krlmlr** [comment]
pkgdown could be more lenient in what it accepts, it's not my hill to die on though.

For now, fledge also creates proper tags with timestamp and message. What's a good way to process this information?

**Comment by daattali** [comment]
I think just having the ability to add dates to each NEWS version is good enough. If pkgdown doesn't support that, then I guess that's a limitation of pkgdown and if you choose to have dates then you can't use pkgdown. No extra processing or anything required - just ability to add date to news

**Comment by krlmlr** [comment]
We don't have infrastructure to store configuration yet, I think this has to be repo-specific.

You still can use pkgdown with dates in the version, it comes out ugly. Maybe if pkgdown ignores HTML comments in NEWS.md? Maybe fledge can add a bullet or free text after the heading?

The easiest route is to make this compatible with pkgdown, one way or another. If you find a formatting for NEWS.md that renders nicely with `pkgdown::build_news()` I'm happy to add dates by default.

**Comment by daattali** [comment]
My request was made independently of pkgdown - I didn't know there's such a tight coupling between fledge and pkgdown. If any change here must play nicely with pkgdown, then I'll step away because I don't use it and can't contribute to this :)

**Comment by krlmlr** [comment]
The other route is to implement configuration for fledge -- a `.fledge` file in the beloved DCF format for instance. That would open the route to many other enhancements that have been requested in the past.

NEWS files generated by fledge are rendered nicely by pkgdown, I don't intend to change this in the near future.

I just checked -- dates in comments are ignored by pkgdown. If we generate a header of the form

```
# fledge 0.8.1.9000 <!-- 2020-05-21 -->
```

it works for both use cases without configuration.

Your call.

**Comment by daattali** [comment]
If the main purpose is to hook into pkgdown, then this request indeed wouldn't make sense.

I was just thinking something like `fledge::commit_version(date=TRUE)` to add dates - if pkgdown doesn't like that, then pkgdown can't be usedwith this. I may be in the minority, but I very often look at NEWS files directly on github. So for me it doesn't matter if a news file is not pkgdown-compatible. Adding it as an HTML comment isn't too useful because that also wouldn't show up in a NEWS.md on github  :) If fledge is meant to work in tandem with pkgdown, then you can close this issue. That's completely fine!

**Comment by krlmlr** [comment]
Bummer.

Another option would be a format like

```md
# fledge 0.8.1.9000

Date: 2020-05-21
```

For CRAN release I'd remove this entry when converting the change log to release notes. For intermediate versions we would have the date in the NEWS. Would that work for you?

**Comment by daattali** [comment]
That seems like a good compromise!

**Comment by krlmlr** [comment]
Would you like to contribute?

**Comment by daattali** [comment]
Not at the moment sorry. Full disclaimer; I don't use fledge... I just saw this package today and looked at the READMe and thought this suggestion might be useful to others. If I ever ending up using this myself and getting more familiar with the packge, I'll dive into your source code then. I don't know how many others find this feature useful so it's obviously not a high priority :p

**Comment by krlmlr** [comment]
Vote here: https://twitter.com/krlmlr/status/1263658654106030081.

**Comment by daattali** [comment]
I've asked this twice on twitter in past years, I'm fairly sure if it comes to a vote I'll be outvoted :)

This can be an optional parameter that doesn't affect anyone who doesn't explicitly choose to opt into it.

**Comment by bastistician** [comment]
> Another option would be a format like
> 
> ```lisp
> # fledge 0.8.1.9000
> 
> Date: 2020-05-21
> 
> - Change 1.
> - Change 2.
> ...
> ```

I'm also not (yet) using **fledge**, but I think it should produce the format expected by R's `utils::news()`, whose help says:
> File ‘NEWS.md’ should contain the news in Markdown (following the CommonMark (<URL: https://commonmark.org/>) specification), with the primary heading level giving the version number after a prefix followed by a space, and optionally followed by a space and a parenthesized ISO 8601 format date.

**Comment by daattali** [comment]
I didn't realize NEWS has a buit in support for this, thanks for letting us know. I'll change all my own packages to that date format. I agree this should be what fledge does if R explicitly says this

**Comment by krlmlr** [comment]
Thanks! Dates are now added if existing headers have them. This allows to keep fledge config-less for now, and also consistent with `?utils::news`.

**Comment by krlmlr** [comment]
For pkgdown, we need

```
news:
  cran_dates: false
```

as described in `?pkgdown::build_news` .
