### ISSUE TITLE
Feature request: micro-version

### ISSUE THREAD

**Issue by zkamvar** [krlmlr/fledge#3]
I was wondering if you would be open to adding functionality for development micro-versioning, where you bump the version number to represent the number of commits from the previous release.

For example, If I updated my package on CRAN to version 2.6.5 a week ago and have made 15 commits since then, the version on GitHub would look like so: 2.6.5.99.15

The inspiration for this came from Gábor Csárdi's answer on StackOverflow: https://stackoverflow.com/a/24274717/2752888

I've implemented a hackey version of this (involving amending commits) in my own repo: https://github.com/grunwaldlab/poppr/tree/master/tools

**Comment by krlmlr** [comment]
Thanks. I'd say this is out of scope for *fledge*, but the two features (micro-versions and automated NEWS generation) can coexist. You can apply the logic for micro-versioning on top of the development version increased by *fledge*.

**Comment by zkamvar** [comment]
Thanks for the quick reply!
