### ISSUE TITLE
`pre_release()`: polish PR appearance

### ISSUE THREAD

**Issue by pat-s** [krlmlr/fledge#52]
Current state: https://github.com/pat-s/duckdb/pull/1

- Title?
- Body?

**Comment by krlmlr** [comment]
Title is good, not sure the contents should be taken from `cran-comments.md`. The instructions will be different depending on if there's automation or not. As a default we could use:

- [ ] Resolve all tasks in `cran-comments.md`
- [ ] Run `fledge::release()`
- [ ] When the package is accepted on CRAN, run `fledge::post_release()`

**Comment by pat-s** [comment]
I'd argue we should use `cran-comments.md` because this file can actually be committed.

The issue is that we need to be ahead of the master branch with one commit to open a PR via the GH CLI.
This could be the change in `cran-comments.md`.

Once the user ticked of the boxes locally and committed `cran-comments.md` again, the trigger which looks for `is_cran_comments_good()` kicks in and starts `release()` (this is how the "release" state in `check_release_state()` is determined atm).

**Comment by krlmlr** [comment]
No action needed here, see https://github.com/r-dbi/RSQLite/pull/329 and a few others.

**Comment by pat-s** [comment]
I think I errored because `cran-comments.md` was in `.gitignore`. We might want to force add.

**Comment by krlmlr** [comment]
Aren't we?

**Comment by pat-s** [comment]
I have in mind I did this at some point but then I would not have errored. 

Need to take a look.
